# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/light.css"
locale: "en-US"
title: "Tolga Üstünkök's Personal Web Site"
description: >- # this means to ignore newlines until "baseurl:"
  Computer engineer and researcher. Currently a research assistant at
  Atılım University, Turkey.
logo: "/assets/images/site-logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tustunkok.github.io" # the base hostname & protocol for your site, e.g. http://example.com
read_time: true
words_per_minute: 200

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

markdown: kramdown
mathjax: true
google_analytics: G-VVMQQ07YVQ

disqus:
  shortname: tustunkok

twitter:
  username: tustunkok

# Build settings
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true


# Site Author
author:
  name: Tolga Üstünkök
  picture: /assets/images/tustunkok_profile_pic.jpg
  email: tolgaustunkok@yahoo.com
  twitter: tustunkok
  links:
    - title: Twitter
      url: https://twitter.com/tustunkok
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/tustunkok
      icon: fab fa-github-square
    - title: ORCID
      url: https://orcid.org/0000-0002-0464-8803
      icon: fab fa-orcid

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/tustunkok
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/tustunkok
    icon: fab fa-github-square
  - title: ORCID
    url: https://orcid.org/0000-0002-0464-8803
    icon: fab fa-orcid
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
